### ISSUE TITLE
Unable to see x3 GridField actions

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-queuedjobs#159] opened 2017-12-21 23:33 UTC
PHP7.0 / framework+cms 4.0.x-dev / queuedjobs dev-master

* Login to the backend as an "ADMIN" user
* Navigate to the "jobs" admin
* Observe (or create) jobs listed in the GridField
* Observe no 'execute', 'pause' or 'resume' actions display in the "Actions" column

Only `GridFieldQueuedJobExecute::__construct()` is called, whereas placing simple debug statements in this classes' other implemented methods does not result in debug logic being called as I would expect. Hacking around in for example `GridFieldEditButton` in _its_ implemented methods, does (obviously) show that they're being called. Not sure what's happening here and cannot spend any more time on it today. (Maybe I'm missing something, it has been known...)

I tried going back as far as `3afac24f411` and buttons still not shown.

**Comment by dhensby** [comment] 2017-12-22 11:54
Is it not a CSS issue causing them to be hidden / have no icon?

**Comment by phptek** [comment] 2017-12-22 20:07
No, I looked at the generated source and the element was empty.

**Comment by phptek** [comment] 2017-12-22 20:07
No, I looked at the generated source and the element was empty.

**Comment by robbieaverill** [comment] 2018-01-26 01:16
Reproduced. For (mostly my) reference, there are the three possible states taken from the SS3 version: 

![image](https://user-images.githubusercontent.com/5170590/35420638-8eb56a62-02a3-11e8-8d35-64cddedbe8da.png)

**Comment by robbieaverill** [comment] 2018-01-26 02:04
The bug was that the GridField is replacing a field that doesn't exist, so it isn't using the custom GridFieldConfig we create. I'm just trying to decide which icons to use to replace the old jQuery UI icons.

**Comment by phptek** [comment] 2018-01-26 02:28
Nice one @robbieaverill while you're at it, don't replace like-for-like (See #45).

**Comment by robbieaverill** [comment] 2018-01-26 02:45
Fix at #164

**Comment by robbieaverill** [comment] 2018-01-26 02:51
Discussed with @phptek over Slack, the fix for this issue is also an improvement towards #45 but doesn't resolve it completely, because we don't have entirely appropriate icons in the silverstripe-admin font icon set. We could switch them for icon images again to close #45, but this is a necessary improvement for now.

**Closed** 2018-01-26 13:09 UTC
Labels: affects/v4, impact/high, type/bug
