### ISSUE TITLE
RunBuildTaskJob chokes on additional parameters

### ISSUE THREAD

**Issue by mikeyc7m** [symbiote/silverstripe-queuedjobs#258] opened 2019-07-05 04:00 UTC
When using the interface to add a job for a BuildTask, the detsils are entered in the "Constructor parameters for job creation (one per line)" field. So if i want parameters, I add a new line for the parameters... however, when the job is saved, the TaskClass is saved into the database with the trailing newline character! When the job goes to execute, it cannot find the matching BuildTask because it tries to match the name + newline = the job is marked as broken.

## PRs
 - [ ] https://github.com/symbiote/silverstripe-queuedjobs/pull/284

**Comment by mikeyc7m** [comment] 2019-07-05 04:01
Using 4.2.2

**Comment by mikeyc7m** [comment] 2019-07-09 09:21
good news! i can fool the system by hitting the queue url directly with the param. for example, 
`https://mysite.nz/dev/tasks/queue/MyTask?myParam=yes`
will correctly add the task to the queue with both TaskClass and paramemeters intact. So it's just a bug with the way the CMS interface is saving the job.

**Comment by robbieaverill** [comment] 2019-07-26 10:40
Hey @mikeyc7m, I'm having trouble reproducing this. Could you help me out? Here's what I'm doing with CWP 2.1.x-dev (SS 4.2.x):

* Log into the admin area
* Go to Jobs
* Create a new job with `...DummyQueuedJob` type
* Add arguments to the constructor:
```
3
foo=bar
```
* Save the job
* Execute via the little play icon button (works fine)
* Do the above again, but then go to `/dev/tasks`
* Run `ProcessJobQueueTask` from the list at the bottom (works fine)

If you could provide some specifics steps to reproduce that'd be cool. Cheers!

**Comment by mikeyc7m** [comment] 2019-08-01 06:40
* log into cms
* go to Jobs modeladmin
* create a new job with `RunBuildTask` type
* add arguments to the constructor 
```
MyTask
myParam=yes
```
* save the job
* execute via the little play button (won't work) or just wait for the cron (won't work either)
* do the above again, but then go to `/dev/tasks`
* run `ProcessJobQueueTask` from the list at the bottom (won't work)

**Comment by mxmclaudel** [comment] 2019-09-21 23:55
I'm having the same issue. Could this be a Windows vs Unix issue? It works fine on my windows server + windows browser. It doesn't work on my windows browser (Chrome/Windows 10) hosted on Unix server.
I've had to add the following for each job parameter:

`preg_replace('/[\x00-\x1F\x7F]/u', '', trim($param));`

**Comment by dnsl48** [comment] 2020-03-09 03:49
Yes, I've just hit the issue. This happens because the Textarea encodes newlines as `\r\n`,
then [we split it by PHP_EOL](https://github.com/symbiote/silverstripe-queuedjobs/blob/4.5.0/src/Controllers/QueuedJobsAdmin.php#L192), which is `\n` on *nix systems and `\r\n` on Windows. This leaves `\r` (carriage return) at the end of every argument when there are more than one given. Eventually that character breaks deserialization.

I will prepare a PR shortly. We should be doing `preg_split('/\R/')` there, not explode.

**Comment by Cheddam** [comment] 2020-03-10 03:31
Fixed in #284.

**Closed by Cheddam** 2020-03-10 03:31 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug

**Comment by dnsl48** [comment] 2020-03-10 03:42
Should end up in `4.5.1` release.

**Comment by dnsl48** [comment] 2020-04-02 01:14
For the versions `<4.5.1`, please use the workaround [mentioned above](https://github.com/symbiote/silverstripe-queuedjobs/issues/258#issuecomment-509564273)
